Class DTSensors.Api.Client.model.CellularStatusEventData Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property cellularStatus As DTSensors.Api.Client.model.CellularStatus;

Storage Default
{
<Data name="CellularStatusEventDataState">
<Value name="1">
<Value>cellularStatus</Value>
</Value>
</Data>
<State>CellularStatusEventDataState</State>
<StreamLocation>^DTSensorsD1EA.CellularStaA083S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
