Class DTSensors.Api.Client.model.ConnectionStatusEventData Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property connectionStatus As DTSensors.Api.Client.model.ConnectionStatus;

Storage Default
{
<Data name="ConnectionStatusEventDataState">
<Value name="1">
<Value>connectionStatus</Value>
</Value>
</Data>
<State>ConnectionStatusEventDataState</State>
<StreamLocation>^DTSensorsD1EA.ConnectionSDD84S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
