Class DTSensors.Api.Client.model.ContactEventData Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property contact As DTSensors.Api.Client.model.Contact;

Storage Default
{
<Data name="ContactEventDataState">
<Value name="1">
<Value>contact</Value>
</Value>
</Data>
<State>ContactEventDataState</State>
<StreamLocation>^DTSensorsD1EA.ContactEven17E8S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
