Class DTSensors.Api.Client.model.DeskOccupancyEventData Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property deskOccupancy As DTSensors.Api.Client.model.DeskOccupancy;

Storage Default
{
<Data name="DeskOccupancyEventDataState">
<Value name="1">
<Value>deskOccupancy</Value>
</Value>
</Data>
<State>DeskOccupancyEventDataState</State>
<StreamLocation>^DTSensorsD1EA.DeskOccupan9D36S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
