Class DTSensors.Api.Client.model.EthernetStatusEventData Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property ethernetStatus As DTSensors.Api.Client.model.EthernetStatus;

Storage Default
{
<Data name="EthernetStatusEventDataState">
<Value name="1">
<Value>ethernetStatus</Value>
</Value>
</Data>
<State>EthernetStatusEventDataState</State>
<StreamLocation>^DTSensorsD1EA.EthernetSta58A5S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
