Class DTSensors.Api.Client.model.inlineresponse20013claimErrors Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property devices As list Of DTSensors.Api.Client.model.inlineresponse20013claimErrorsdevices;

Property kits As list Of DTSensors.Api.Client.model.inlineresponse20013claimErrorskits;

Storage Default
{
<Data name="inlineresponse20013claimErrorsState">
<Value name="1">
<Value>devices</Value>
</Value>
<Value name="2">
<Value>kits</Value>
</Value>
</Data>
<State>inlineresponse20013claimErrorsState</State>
<StreamLocation>^DTSensorsD1EA.inlinerespo926BS</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
