Class DTSensors.Api.Client.model.inlineresponse2005 Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property metrics As DTSensors.Api.Client.model.DataConnectorMetrics;

Storage Default
{
<Data name="inlineresponse2005State">
<Value name="1">
<Value>metrics</Value>
</Value>
</Data>
<State>inlineresponse2005State</State>
<StreamLocation>^DTSensorsD1EA.inlinerespo6373S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
