Class DTSensors.Api.Client.model.inlineresponse20013 Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property claimErrors As DTSensors.Api.Client.model.inlineresponse20013claimErrors;

Property claimedDevices As list Of DTSensors.Api.Client.model.inlineresponse20013claimedDevices;

Storage Default
{
<Data name="inlineresponse20013State">
<Value name="1">
<Value>claimErrors</Value>
</Value>
<Value name="2">
<Value>claimedDevices</Value>
</Value>
</Data>
<State>inlineresponse20013State</State>
<StreamLocation>^DTSensorsD1EA.inlinerespo3060S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
