Class DTSensors.Api.Client.model.inlineresponse2008 Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

/// The invite URL.
Property inviteUrl As %String(MAXLEN = "");

Storage Default
{
<Data name="inlineresponse2008State">
<Value name="1">
<Value>inviteUrl</Value>
</Value>
</Data>
<State>inlineresponse2008State</State>
<StreamLocation>^DTSensorsD1EA.inlinerespoA6B2S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
