Class DTSensors.Api.Client.model.inlineresponse2001 Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property batchErrors As list Of DTSensors.Api.Client.model.inlineresponse2001batchErrors;

Storage Default
{
<Data name="inlineresponse2001State">
<Value name="1">
<Value>batchErrors</Value>
</Value>
</Data>
<State>inlineresponse2001State</State>
<StreamLocation>^DTSensorsD1EA.inlinerespoA072S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
