Class DTSensors.Api.Client.model.MotionEventData Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property motion As DTSensors.Api.Client.model.Motion;

Storage Default
{
<Data name="MotionEventDataState">
<Value name="1">
<Value>motion</Value>
</Value>
</Data>
<State>MotionEventDataState</State>
<StreamLocation>^DTSensorsD1EA.MotionEventF4C4S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
