Class DTSensors.Api.Client.model.NetworkStatusEventData Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property networkStatus As DTSensors.Api.Client.model.NetworkStatus;

Storage Default
{
<Data name="NetworkStatusEventDataState">
<Value name="1">
<Value>networkStatus</Value>
</Value>
</Data>
<State>NetworkStatusEventDataState</State>
<StreamLocation>^DTSensorsD1EA.NetworkStatCF3ES</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
