Class DTSensors.Api.Client.model.ObjectPresentEventData Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property objectPresent As DTSensors.Api.Client.model.ObjectPresent;

Storage Default
{
<Data name="ObjectPresentEventDataState">
<Value name="1">
<Value>objectPresent</Value>
</Value>
</Data>
<State>ObjectPresentEventDataState</State>
<StreamLocation>^DTSensorsD1EA.ObjectPrese7BC8S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
