Class DTSensors.Api.Client.model.ObjectPresentCountEventData Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property objectPresentCount As DTSensors.Api.Client.model.ObjectPresentCount;

Storage Default
{
<Data name="ObjectPresentCountEventDataState">
<Value name="1">
<Value>objectPresentCount</Value>
</Value>
</Data>
<State>ObjectPresentCountEventDataState</State>
<StreamLocation>^DTSensorsD1EA.ObjectPreseDD42S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
