Class DTSensors.Api.Client.model.StreamEvent Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

/// 
/// * This property is required.
Property result As DTSensors.Api.Client.model.StreamEventresult;

Storage Default
{
<Data name="StreamEventState">
<Value name="1">
<Value>result</Value>
</Value>
</Data>
<State>StreamEventState</State>
<StreamLocation>^DTSensors.ApiD1EA.StreamEventS</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
