Class DTSensors.Api.Client.model.StreamEventresult Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

/// 
/// * This property is required.
Property event As DTSensors.Api.Client.model.Event;

Storage Default
{
<Data name="StreamEventresultState">
<Value name="1">
<Value>event</Value>
</Value>
</Data>
<State>StreamEventresultState</State>
<StreamLocation>^DTSensorsD1EA.StreamEvent9F70S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
