Class DTSensors.Api.Client.model.TouchCountEventData Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property touchCount As DTSensors.Api.Client.model.TouchCount;

Storage Default
{
<Data name="TouchCountEventDataState">
<Value name="1">
<Value>touchCount</Value>
</Value>
</Data>
<State>TouchCountEventDataState</State>
<StreamLocation>^DTSensorsD1EA.TouchCountED88FS</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
