Class DTSensors.Api.Client.model.WaterPresentEventData Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property waterPresent As DTSensors.Api.Client.model.WaterPresent;

Storage Default
{
<Data name="WaterPresentEventDataState">
<Value name="1">
<Value>waterPresent</Value>
</Value>
</Data>
<State>WaterPresentEventDataState</State>
<StreamLocation>^DTSensorsD1EA.WaterPresenC40CS</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
