Class ZorgAB.Api.Client.model.AuthorizationEndpoint Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property authorizationEndpointuri As %String(MAXLEN = "");

Storage Default
{
<Data name="AuthorizationEndpointState">
<Value name="1">
<Value>authorizationEndpointuri</Value>
</Value>
</Data>
<State>AuthorizationEndpointState</State>
<StreamLocation>^CONNECTORS34FF.Authorizati8952S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
