Class CONNECTORSPKG.ZorgAB.Api.Client.model.ResourceEndpoint Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property resourceEndpointuri As %String(MAXLEN = "");

Storage Default
{
<Data name="ResourceEndpointState">
<Value name="1">
<Value>resourceEndpointuri</Value>
</Value>
</Data>
<State>ResourceEndpointState</State>
<StreamLocation>^CONNECTORS34FF.ResourceEndEA94S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
