Class CONNECTORSPKG.ZorgAB.Api.Client.model.Interfaceversie Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property interfaceversieId As %String(MAXLEN = "");

Storage Default
{
<Data name="InterfaceversieState">
<Value name="1">
<Value>interfaceversieId</Value>
</Value>
</Data>
<State>InterfaceversieState</State>
<StreamLocation>^CONNECTORS34FF.Interfaceve570CS</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
