Class CONNECTORSPKG.ZorgAB.Api.Client.model.TokenEndpoint Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property tokenEndpointuri As %String(MAXLEN = "");

Storage Default
{
<Data name="TokenEndpointState">
<Value name="1">
<Value>tokenEndpointuri</Value>
</Value>
</Data>
<State>TokenEndpointState</State>
<StreamLocation>^CONNECTORSPK34FF.TokenEndpointS</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
