Class CONNECTORSPKG.VektisAGB.Api.Client.model.TestModel Extends (%SerialObject, %JSON.Adaptor, %XML.Adaptor) [ Inheritance = left, ProcedureBlock ]
{

Property MultipliedBySelf As %Integer;

Property Number As %Integer;

Storage Default
{
<Data name="TestModelState">
<Value name="1">
<Value>MultipliedBySelf</Value>
</Value>
<Value name="2">
<Value>Number</Value>
</Value>
</Data>
<State>TestModelState</State>
<StreamLocation>^CONNECTORSPKG.VeD8C0.TestModelS</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
