Class DTSensors.Api.Authenticate Extends %RegisteredObject
{

/// Service Account ID
Property ServiceAccountID As %String [ InitialExpression = "cpkpnag4ltn000c618gg" ];

/// Service Account Email
Property ServiceAccountEmail As %String [ InitialExpression = "cpkpnag4ltn000c618gg@cpkpleo2c3i833ad91q0.serviceaccount.d21s.com" ];

/// Service Account Secret
Property ServiceAccountSecret As %String [ InitialExpression = "869dca2f701f418da17cc949e2a5ee92" ];

}
